Update configmap.yaml
netdata/helmchart pull request #141
Opened 2020-09-19 13:46 UTC by MansM

fixes: https://github.com/netdata/helmchart/issues/140

tested with helm 2 and 3

2020-09-20 13:58 UTC, ilyam8 commented on templates/configmap.yaml
> +{{ if and .Values.child.enabled .Values.sd.child.enabled .Values.sd.child.configmap.from }}
This works, but i think we need to remove only the right delimiter `-`

2020-09-20 13:58 UTC, ilyam8 commented on templates/configmap.yaml
> +{{ if .Values.child.enabled }}
same

2020-09-20 14:03 UTC, ilyam8 commented on templates/configmap.yaml
> +{{ if and .Values.child.enabled .Values.sd.child.enabled .Values.sd.child.configmap.from }}
otherwise there is extra empty line

2020-09-21 01:50 UTC, ncmans approved these changes

2020-09-21 14:43 UTC, knatsakis approved these changes

2020-09-22 04:45 UTC, prologic requested changes
LGTM but @ilyam8 is [right](https://pkg.go.dev/text/template#hdr-Text_and_spaces) Pleaseamend.

2020-09-25 15:23 UTC, MansM commented
I am sorry, I am still down with a nasty fever and didnt had time to get to it earlier

2020-09-25 17:10 UTC, ilyam8 approved these changes

2020-09-28 04:22 UTC, prologic approved these changes

2020-09-28 12:07 UTC, knatsakis commented
Thank you for your contribution @MansM

2020-09-28 12:07 UTC, merged