Create CODE_OF_CONDUCT.md
netdata/helmchart pull request #181
Opened 2020-11-03 17:43 UTC by OdysLam

2020-11-06 13:37 UTC, knatsakis requested changes

2020-11-06 13:37 UTC, knatsakis commented on CODE_OF_CONDUCT.md
> +This repository part of the Netdata Community, thus all contributors should follow our [Code of Conduct](https://github.com/netdata/netdata/blob/master/CODE_OF_CONDUCT.md).
```suggestion
This repository is part of the Netdata Community, thus all contributors should follow our [Code of Conduct](https://github.com/netdata/netdata/blob/master/CODE_OF_CONDUCT.md).
```

2020-11-09 09:08 UTC, knatsakis approved these changes

2020-11-09 09:32 UTC, ilyam8 approved these changes

2020-11-10 10:44 UTC, merged