remove ncmans prologic from CODEOWNERS
netdata/helmchart pull request #182
Opened 2020-11-06 14:55 UTC by ilyam8

2020-11-06 15:07 UTC, knatsakis commented
> @knatsakis i guess we need to remove @cakrit too.
> 
> whom to add? @Ferroin and probably me?

Yes. Let's do that.

2020-11-06 15:08 UTC, knatsakis approved these changes

2020-11-06 15:08 UTC, knatsakis requested changes

2020-11-06 15:08 UTC, knatsakis commented on .github/CODEOWNERS
> +* @cakrit @knatsakis
```suggestion
* @Ferroin @ilyam8 @knatsakis 
```

2020-11-06 15:09 UTC, knatsakis requested changes

2020-11-06 15:09 UTC, knatsakis commented on .github/CODEOWNERS
> +* @cakrit @knatsakis
```suggestion
* @Ferroin @ilyam8 @knatsakis
```

2020-11-06 18:26 UTC, Ferroin approved these changes

2020-11-09 09:35 UTC, knatsakis approved these changes

2020-11-09 09:37 UTC, merged