restrictions to psp
netdata/helmchart pull request #239
Opened 2021-10-29 19:48 UTC by M4itee

ref #148 
restrictions to the PSP:
- decrease in capabilities,
- privileged setting removed.

2021-11-01 15:24 UTC, knatsakis approved these changes

2021-11-02 07:43 UTC, rsawer commented
did this pass functionality tests?

2021-11-02 08:56 UTC, ilyam8 requested changes
Hold on with merging. I need to check it. I doubt that we can remove `privileged` from the sysctlInitContainer. That is the whole purpose of it - to be privileged and to be able to do changes on the host system (not sure tho).

2021-11-10 11:31 UTC, M4itee commented
@ilyam8 did you had a time to poke this issue with some kind of stick or not yet? :)

2021-11-12 12:19 UTC, ilyam8 requested changes

2021-11-12 12:19 UTC, ilyam8 commented on charts/netdata/templates/psp.yaml
> +    - SYS_PTRACE
```suggestion
  allowedCapabilities:
    - SYS_PTRACE
    - CAP_SYS_ADMIN
```

Those are needed by [apps.plugin](https://github.com/netdata/netdata/tree/master/collectors/apps.plugin#appsplugin) and [cgroups.plugin](https://github.com/netdata/netdata/tree/master/collectors/cgroups.plugin#cgroupsplugin).

See https://github.com/netdata/helmchart/blob/915ea3bd202aef27385638dc73fc61071cecd40b/charts/netdata/templates/daemonset.yaml#L157-L161

And I think that 'allowedCapabilities' is better (more secure) than 'allowedCapabilities'.

2021-11-12 12:19 UTC, ilyam8 commented on charts/netdata/templates/psp.yaml
> -  privileged: true
'privileged: true' is needed for [sysctlInitContainer](https://github.com/netdata/helmchart/blob/915ea3bd202aef27385638dc73fc61071cecd40b/charts/netdata/templates/daemonset.yaml#L48-L56).

I don't know how people use this option (or is it used at all). My understanding is that sysctlInitContainer is supposed to perform changes on the host system thus needs to be priviliged.

2021-11-12 12:30 UTC, ilyam8 commented on charts/netdata/templates/psp.yaml
> -  privileged: true
Related article: https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/

2021-11-17 09:08 UTC, ShimonOhayon approved these changes

2021-11-17 09:48 UTC, ilyam8 approved these changes

2021-11-17 10:37 UTC, merged