rm service discovery sidecar for Netdata v3.0+
netdata/helmchart pull request #459
Opened 2024-12-31 12:08 UTC by ilyam8

[service-discovery sidecar](https://github.com/netdata/agent-service-discovery) is no longer needed as its functionality is built into go.d.plugin.

This change was announced in [v2.1.0 deprecation notice](https://github.com/netdata/netdata/releases/tag/v2.1.0#v210-deprecation-notice).

2025-01-03 07:43 UTC, witalisoft approved these changes

2025-01-03 08:06 UTC, M4itee requested changes
I'm ok with the change but please keep `yaml` extensions the same - `k8s.yml` stands out from other `.yaml`'s

2025-01-03 08:20 UTC, ilyam8 commented
The existing configuration has a `.yml` extension, so I created a new one with the same extension.

https://github.com/netdata/helmchart/blob/master/charts/netdata/sdconfig/child.yml

2025-01-03 08:23 UTC, ilyam8 commented on charts/netdata/templates/_helpers.tpl
> +{{- if semverCompare "<3.0-0" .Chart.AppVersion -}}
This will change if we decide not to do a major release. See [this Slack discussion](https://netdata-cloud.slack.com/archives/CNLAM2B19/p1735663645012739) for details.

2025-01-10 19:08 UTC, ilyam8 commented
@M4itee can you answer to https://github.com/netdata/helmchart/pull/459#issuecomment-2568839549?

2025-01-22 11:42 UTC, ilyam8 commented
Changed version check to < 2.2 as we decided not to do a major release.

2025-01-24 14:04 UTC, M4itee approved these changes

2025-01-26 14:42 UTC, merged